### ISSUE TITLE
Add support for text ellipsis

### ISSUE THREAD

**Issue by ssured** [jxnblk/axs#19]
Adding ellipsis to text would be really nice

https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/

Thanks!

**Comment by jxnblk** [comment]
Why would this *not* work in Axs?

**Comment by ssured** [comment]
What I intended to communicate is something like the snippet below:

```
<Text is='h1' ellipsis>
  This is potentially a very long title. This is potentially a very long title. This is potentially a very long title. This is potentially a very long title. 
</Text>
```

Its true you can currently do this using regular css, but it would be nice to add, as ellipsis is something I use very often. It helps to keep pages from breaking if you have no knowledge of the maximum length of titles.

**Comment by jxnblk** [comment]
I'd suggest making a Truncate component, something like:

```js
const Truncate = props => (
  <Text {...props}
    css={{
      overflow: 'hidden',
      whiteSpace: 'nowrap',
      textOverflow: 'ellipsis'
    }}
  />
)
```

**Comment by ssured** [comment]
Thanks; that's how I do it now. I thought adding the keyword `ellipsis` would be a nice addition to your library, this for sure works
